config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'integrations#index'

  resources :configured_services, except: :show do
    resources :data_sources, except: :show do
      member do
        # This is the route for data sources pushing to the app, not for the app
        # itself pushing.
        post 'push'
      end
    end
    resources :data_destinations, except: :show
  end
  resources :integrations, only: [:index, :new, :create, :destroy] do
    collection do
      post 'save_draft'
    end
  end

  namespace :oauth do
    get :google
  end
end

app/models/concerns/data_source/type.rb
# This module includes functionality for the data source type, including single
# table inheritance. Follow these steps to add a new data source type:
#
#   1. Define a class for the data source type in the DataSources module, for
#      example, DataSources::Odk.
#   2. Add the demodulized class name (for example, 'Odk') to TYPE_CLASS_NAMES.
#   3. See ModelAttributes::Settings for ways to store data source settings.
#   4. Define a data processor that can parse data from the data source type:
#      see DataSource::Type::Processor and DataProcessor::Base.
#   5. Define the rule types applicable to the data source type: see
#      DataSource::Type::HasRules and Rule::Base.
#
module DataSource::Type
  extend ActiveSupport::Concern

  include ModelAttributes::Type
  include ModelAttributes::Settings
  include DataSource::Type::Processor
  include DataSource::Type::HasRules

  # Whitelist of demodulized names of data source classes
  TYPE_CLASS_NAMES = %w[Odk].freeze

  class_methods do
    def type_class_names
      TYPE_CLASS_NAMES.map { |name| "DataSources::#{name}" }
    end
  end
end

app/models/concerns/data_source/type/has_rules.rb
# This module includes functionality for accessing the data source type's list
# of supported rules. An alert associated with a data source can be triggered
# only by one of the supported rules of the data source's type. For example, a
# rule designed to evaluate something ODK-specific cannot be applied to incoming
# data from another data source type.
#
# We can distinguish between a rule type -- represented by a rule class -- and a
# fully parameterized rule, which is represented by a rule object. The word
# "rule" can refer to either concept, similar to how the word "filter" can mean
# either a filtering process or an application of such a process. However, this
# module is concerned solely with rule types: you should read references to
# "supported rules" as having to do with rule types. That said, in general,
# unless specified otherwise, the term "rule" usually refers to a parameterized
# rule: the app uses rule types in fewer places.
#
# An Alert object validates that its rule type is supported by the alert's
# associated data sources, and it also validates its rule object in other ways.
#
module DataSource::Type::HasRules
  extend ActiveSupport::Concern

  included do
    # Avoid accessing this class attribute directly: use ::supported_rules and
    # ::with_rules.
    class_attribute :_rules, instance_accessor: false, instance_predicate: false
    self._rules = [].freeze
  end

  class_methods do
    def with_rules(rule_classes)
      unless rule_classes.all? { |rule_class| rule_class < Rule::Base }
        raise ArgumentError
      end
      # The class inherits its superclass's supported rules.
      self._rules = superclass._rules + rule_classes
      _rules.freeze
    end

    def supported_rules
      _rules
    end
  end
end

app/models/concerns/data_source/type/processor.rb
# This module includes functionality for the data source's data processor: see
# DataProcessor::Base. Because data formats vary, each data source type is
# typically associated with its own data processor class.
#
# Use ::with_processor to set the data source type's data processor class.
# Otherwise, it defaults to the data processor with the same demodulized class
# name as the data source. Once the data processor class is set, a data source
# object may instantiate a data processor object using #processor.
#
module DataSource::Type::Processor
  extend ActiveSupport::Concern

  included do
    # Avoid accessing this class attribute directly: use ::processor_class and
    # ::with_processor.
    class_attribute :_processor, instance_accessor: false,
                    instance_predicate: false
  end

  class_methods do
    def with_processor(processor_class)
      self._processor = processor_class
    end

    def processor_class
      self._processor || "DataProcessor::#{name.demodulize}".constantize
    end
  end

  def processor
    self.class.processor_class.new(self)
  end
end

app/models/concerns/data_source/type/rules.rb
# This module includes functionality for accessing the data source type's list
# of supported rules. An alert associated with a data source can be triggered
# only by one of the supported rules of the data source's type. For example, a
# rule designed to evaluate something ODK-specific cannot be applied to incoming
# data from another data source type.
#
# We can distinguish between a rule type -- represented by a rule class -- and a
# fully parameterized rule, which is represented by a rule object. The word
# "rule" can refer to either concept, similar to how the word "filter" can mean
# either a filtering process or an application of such a process. However, this
# module is concerned solely with rule types: you shoud read references to
# "supported rules" as having to do with rule types. That said, in general,
# unless specified otherwise, the term "rule" usually refers to a parameterized
# rule: the app uses rule types in fewer places.
#
# An Alert object validates that its rule type is supported by the alert's
# associated data sources, and it also validates its rule object in other ways.
#
module DataSource::Type::Rules
  extend ActiveSupport::Concern

  included do
    # Avoid accessing this class attribute directly: use ::supported_rules and
    # ::with_rules.
    class_attribute :_rules, instance_accessor: false, instance_predicate: false
    self._rules = [].freeze
  end

  class_methods do
    def with_rules(rule_classes)
      unless rule_classes.all? { |rule_class| rule_class < Rule::Base }
        raise ArgumentError
      end
      # The class inherits its superclass's supported rules.
      self._rules = superclass._rules + rule_classes
      _rules.freeze
    end

    def supported_rules
      _rules
    end
  end
end

app/models/data_source.rb
class DataSource < ApplicationRecord
  include Draftable
  include ModelAttributes::Name
  include ServiceProvided
  include DataSource::Type

  with_draft_attribute :data_source_id

  has_many :data_source_alerts
  has_many :alerts, through: :data_source_alerts
  before_destroy :destroy_alerts

  protected

  def destroy_alerts
    multi_source_alerts = DataSourceAlert
                            .group(:alert_id)
                            .having('bool_or(data_source_id = ?)', id)
                            .having('count(*) > 1')
    # TODO: Develop an approach for destroying multi-source alerts.
    return false if multi_source_alerts.any?
    alerts.destroy_all
  end
end

app/models/data_sources/odk.rb
class DataSources::Odk < DataSource
  with_settings :form_id
  validate :validate_form_id

  with_rules [
    Rules::Odk::NumericEquality,
    Rules::Odk::GreaterThan,
    Rules::Odk::LessThan,
    Rules::Odk::StringEquality,
    Rules::Odk::Contain,
    Rules::Odk::StartWith,
    Rules::Odk::EndWith,
    Rules::Odk::RegexpMatch
  ]

  alias_method :server, :configured_service

  protected

  def validate_form_id
    message = if !form_id.is_a?(String)
                'Form ID is invalid'
              elsif form_id.blank?
                "Form ID can't be blank"
              end
    errors.add :settings, message unless message.nil?
  end
end

app/controllers/data_sources_controller.rb
class DataSourcesController < ApplicationController
  include ConfiguredServicePathHelpers

  before_action :set_service
  before_action :set_source, only: [:edit, :update, :destroy, :push]
  skip_before_action :verify_authenticity_token, only: :push

  before_action do
    add_configured_service_breadcrumb
    add_breadcrumb @service.name, edit_configured_service_path(@service)
    add_breadcrumb @service.class.terminology.data_source.pluralize.titleize,
                   configured_service_data_sources_path(@service)
  end

  def index
    @sources = @service.data_sources.order_by_name.load
  end

  def new
    @source = @service.class.data_source_class.new
    render_new
  end

  def create
    @source = DataSource.new(source_params)
    if @source.save
      @source.save_draft
      redirect_to new_integration_path
    else
      render_new
    end
  end

  def edit
    render_edit
  end

  def update
    if @source.update(source_params)
      redirect_to configured_service_data_sources_path(@service)
    else
      render_edit
    end
  end

  def destroy
    @source.destroy
    redirect_to configured_service_data_sources_path(@service)
  end

  # This is the action for data sources pushing to the app, not for the app
  # itself pushing.
  def push
    # Some data sources stop pushing unless they receive a successful response,
    # so #push should never raise an error.
    begin
      @source.processor.process request
    rescue => e
      Rails.logger.error e.backtrace.join("\n")
    end
    head 200
  end

  protected

  def set_service
    @service = ConfiguredService.find(params[:configured_service_id])
  end

  def set_source
    @source = @service.data_sources.find(params[:id])
  end

  def render_new
    add_breadcrumb 'Add ' + @service.class.terminology.data_source.titleize
    render 'new'
  end

  def source_params
    source_class = @service.class.data_source_class
    settings = source_class.supported_settings.map(&:to_sym)
    source_params = params.permit(:configured_service_id, :name,
                                  settings: settings)
    source_params[:type] = source_class.name
    source_params
  end

  def render_edit
    add_breadcrumb @source.name
    render 'edit'
  end
end

app/views/data_sources/_form_errors.html.erb
<% if @source.errors.any? %>
  <div class="panel panel-danger">
    <div class="panel-heading">
      Invalid <%= @service.class.terminology.data_source.titleize %>
    </div>
    <div class="panel-body">
      <p>
        There
        <% if @source.errors.size == 1 %>
          was a problem
        <% else %>
          were problems
        <% end %>
        saving the <%= @service.class.terminology.data_source %>:
      </p>
      <ul>
        <% @source.errors.each do |attribute, error| %>
          <li>
            <% unless attribute == :settings %>
              <%= DataSource.human_attribute_name(attribute) %>
            <% end %>
            <%= error %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/data_sources/_form_fields.html.erb
<div class="form-group">
  <%= label_tag :name, nil, class: 'col-md-2 control-label' %>
  <div class="col-md-6">
    <%= text_field_tag :name, @source.name, placeholder: 'Name', required: true,
                       class: 'form-control' %>
  </div>
</div>
<div class="form-group">
  <%= label_tag 'settings[form_id]', 'Form ID',
                class: 'col-md-2 control-label' %>
  <div class="col-md-6">
    <%= text_field_tag 'settings[form_id]', @source.form_id,
                       placeholder: 'Form ID', required: true,
                       class: 'form-control' %>
  </div>
</div>

app/views/data_sources/edit.html.erb
<%= render 'form_errors' %>

<%= form_tag configured_service_data_source_path(@service, @source),
             method: :patch, class: 'form-horizontal' do %>
  <%= render 'form_fields' %>

  <div class="form-group">
    <div class="col-md-offset-2 col-md-10">
      <%= button_tag icon('floppy-o', 'Save'), class: 'btn btn-default' %>
      <%= link_to icon('close', 'Cancel'),
                  configured_service_data_sources_path(@service), role: :button,
                  class: 'btn btn-default' %>
      <%= link_to icon('trash-o', 'Delete'),
                  configured_service_data_source_path(@service, @source),
                  method: :delete, role: :button,
                  class: 'btn btn-danger btn-delete',
                  data: { confirm: "Are you sure you want to delete #{@source.name}?" } %>
    </div>
  </div>
<% end %>

app/views/data_sources/index.html.erb
<div class="collection-actions">
  <% term = @service.class.terminology.data_source.titleize %>
  <%= link_to icon('plus', 'Add ' + term),
              new_configured_service_data_source_path(@service), role: :button,
              class: 'btn btn-success' %>
</div>

<% if @sources.none? %>
  <div class="panel panel-default">
    <div class="panel-body">
      No <%= @service.class.terminology.data_source.pluralize %> have been
      configured yet for <strong><%= @service.name %></strong>.
    </div>
  </div>
<% else %>
  <table class="table table-hover table-borderless">
    <tbody>
      <% @sources.each do |source| %>
        <tr>
          <td>
            <span class="member-actions">
              <%= link_to icon('pencil'),
                          edit_configured_service_data_source_path(@service, source) %>
              <%= link_to icon('trash-o', class: 'text-danger'),
                          configured_service_data_source_path(@service, source),
                          method: :delete,
                          data: { confirm: "Are you sure you want to delete #{source.name}?" } %>
            </span>
            <%= source.name %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/data_sources/new.html.erb
<%= render 'form_errors' %>

<%= form_tag configured_service_data_sources_path(@service), method: :post,
             class: 'form-horizontal' do %>
  <%= render 'form_fields' %>

  <div class="form-group">
    <div class="col-md-offset-2 col-md-10">
      <% term = @service.class.terminology.data_source.titleize %>
      <%= button_tag icon('plus', 'Add ' + term), class: 'btn btn-success' %>
      <%= link_to icon('close', 'Cancel'), :back, role: :button,
                  class: 'btn btn-default' %>
    </div>
  </div>
<% end %>