config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'integrations#index'

  resources :configured_services, except: :show do
    resources :data_sources, except: :show do
      member do
        # This is the route for data sources pushing to the app, not for the app
        # itself pushing.
        post 'push'
      end
    end
    resources :data_destinations, except: :show
  end
  resources :integrations, only: [:index, :new, :create, :destroy] do
    collection do
      post 'save_draft'
    end
  end

  namespace :oauth do
    get :google
  end
end

app/models/concerns/configured_service/type.rb
# This module includes functionality for the configured service type, including
# single table inheritance. There is a separate configured service subclass for
# each service technology. Follow these steps to add a new configured service
# type:
#
#   1. Define a class for the configured service type in the ConfiguredServices
#      module, for example, ConfiguredServices::Odk.
#   2. Add the demodulized class name (for example, 'Odk') to TYPE_CLASS_NAMES.
#   3. Provide a human-friendly name for the service technology using
#      ::with_technology_name.
#      TODO: Update this comment.
#   4. Mark the service as a data source provider and/or a data destination
#      provider: see ConfiguredServices::Type::Provider.
#   5. See ModelAttributes::Settings for ways to store configured service
#      settings.
#
module ConfiguredService::Type
  extend ActiveSupport::Concern

  include ModelAttributes::Type
  include ModelAttributes::Settings
  include ConfiguredService::Type::Provider
  include ConfiguredService::Type::Terminology
  include ConfiguredService::Type::Oauthable

  # Whitelist of demodulized names of configured service classes
  TYPE_CLASS_NAMES = %w[Gmail Odk].freeze

  class_methods do
    def type_class_names
      TYPE_CLASS_NAMES.map { |name| "ConfiguredServices::#{name}" }
    end
  end
end

app/models/concerns/configured_service/type/oauthable.rb
module ConfiguredService::Type::Oauthable
  extend ActiveSupport::Concern

  included do
    has_one :oauth_token, dependent: :destroy

    class_attribute :_oauthable
    self._oauthable = false
  end

  class_methods do
    def oauthable
      self._oauthable = true
    end

    def oauthable?
      _oauthable
    end

    def oauthable!
      raise 'not oauthable' unless oauthable?
    end
  end

  def oauth_token
    self.class.oauthable!
    super
  end
end

app/models/concerns/configured_service/type/provider.rb
# This module provides functionality for services that are a data source
# provider and/or a data destination provider. Use ::provides to mark a service
# as a data source provider and/or a data destination provider. Use ::provides?
# to determine whether a service is a data source provider, a data destination
# provider, or both. Examples:
#
#   # We mark the New York Times API as a data source provider.
#   class ConfiguredServices::NyTimes
#     provides :data_source
#
#     ...
#   end
#
#   # We mark Salesforce as both a data source and data destination provider.
#   class ConfiguredServices::Salesforce
#     provides :data_source, :data_destination
#
#     ...
#   end
#
#   ConfiguredServices::NyTimes.provides? :data_source
#       #=> true
#   ConfiguredServices::NyTimes.provides? :data_destination
#       #=> false
#   ConfiguredServices::Salesforce.provides? :data_source
#       #=> true
#   ConfiguredServices::Salesforce.provides? :data_destination
#       #=> true
#
module ConfiguredService::Type::Provider
  extend ActiveSupport::Concern

  included do
    # Avoid accessing this class attribute directly: use ::provides and
    # ::provides?.
    class_attribute :_provider
    self._provider = HashWithIndifferentAccess.new({
      data_source: false,
      data_destination: false
    })

    # All CertifiedService subclasses will have :data_sources and
    # :data_destinations associations, even if they do not provide them.
    # Otherwise, because of the single table inheritance, we would have to give
    # up on recognized bi-directional associations: the :inverse_of option of
    # ::belongs_to and ::has_many does not play well with single table
    # inheritance. However, we override #data_sources and #data_destinations
    # below to raise an error if they are called by an object whose service does
    # not provide them.
    has_many :data_sources, dependent: :destroy
    has_many :data_destinations, dependent: :destroy
  end

  class_methods do
    # If a configured service class is a data source provider and/or a data
    # destination provider, its subclasses must be as well: there is no
    # "unprovide" method.
    def provides(*targets)
      clone_superclass_providers
      targets.each do |target|
        raise ArgumentError unless _provider.key? target
        _provider[target] = true
      end
    end

    def provides?(target)
      _provider.fetch target
    end

    # Asserts that the service is a provider of the specified kind.
    def provides!(target)
      raise "not a #{target} provider" unless provides? target
    end

    # Each service that is a data source provider is associated with its own
    # data source class. #data_source_class returns that class.
    def data_source_class
      provides! :data_source
      name = 'DataSources::' + self.name.demodulize
      raise ArgumentError unless DataSource.type_class_names.include? name
      name.constantize
    end

    # Each service that is a data destination provider is associated with its
    # own data destination class. #data_destination_class returns that class.
    def data_destination_class
      provides! :data_destination
      name = 'DataDestinations::' + self.name.demodulize
      raise ArgumentError unless DataDestination.type_class_names.include? name
      name.constantize
    end

    protected

    def clone_superclass_providers
      # The class's provider settings are the same object as those of its
      # superclass if and only if the class's provider settings have not been
      # cloned yet.
      return unless _provider.equal? superclass._provider
      # The class inherits its superclass's provider settings.
      self._provider = superclass._provider.dup
    end
  end

  def data_sources
    self.class.provides! :data_source
    super
  end

  def data_destinations
    self.class.provides! :data_destination
    super
  end
end

app/models/concerns/configured_service/type/terminology.rb
# This module includes functionality for accessing the name of the service
# technology.
# TODO: Update comment.
module ConfiguredService::Type::Terminology
  extend ActiveSupport::Concern

  TERMINOLOGY = [:service, :configured_service, :data_source, :data_destination]

  included do
    # Avoid accessing this class attribute directly: use ::terminology and
    # ::with_terminology.
    class_attribute :_terminology, instance_accessor: false,
                    instance_predicate: false
    self._terminology = {
      service: 'Service',
      configured_service: 'configured service',
      data_source: 'data source',
      data_destination: 'data destination'
    }.freeze
  end

  class_methods do
    def with_terminology(terminology)
      clone_superclass_terminology
      terminology.each do |key, value|
        sym_key = key.to_sym
        raise ArgumentError unless TERMINOLOGY.include? sym_key
        if sym_key == :data_source || sym_key == :data_destination
          provides! sym_key
        end
        _terminology[sym_key] = value.dup.freeze
      end
      _terminology.freeze
    end

    def terminology
      terminology = OpenStruct.new(_terminology)
      terminology.delete_field :data_source unless provides? :data_source
      unless provides? :data_destination
        terminology.delete_field :data_destination
      end
      terminology.freeze
    end

    private

    def clone_superclass_terminology
      # The class's terminology is the same object as the terminology of its
      # superclass if and only if the class's terminology has not been cloned
      # yet.
      return unless _terminology.equal? superclass._terminology
      # The class inherits its superclass's terminology.
      self._terminology = superclass._terminology.dup
    end
  end
end

app/models/configured_service.rb
# Congenial Enigma will support data received from multiple services -- for
# example, ODK and DHIS2 -- as well as data received from multiple destinations,
# for example, Gmail and Twilio. When creating an integration, users tell us,
# among other information:
#
#   1. The service from which data is sent (for example, ODK or DHIS2)
#   2. What account or configuration to use for that service (for example, a
#      particular ODK Aggregate server)
#   3. The service that receives the data (for example, Gmail or Twilio)
#   4. What account or configuration to use for this second service (for
#      example, a particular Gmail account)
#
# A ConfiguredService record encapsulates categories (2) and (4) above: it
# represents a fully configured service, whether that service is a data source
# provider, a data destination provider, or both. The primary role of the
# configured service is to store credentials or otherwise provide a connection
# to a service. For example, if ODK is the service, a particular ODK Aggregate
# server is the configured service.
#
# A single configured service may have multiple data sources. For example, a
# single ODK Aggregate server may house multiple forms. The DataSource model
# determines how to actually process incoming data: the ConfiguredService model
# simply lays the foundation for DataSource.
#
# Likewise, a single configured service may have multiple data destinations. A
# service may also be both a data source provider and a data destination
# provider.
#
# Depending on the context, the term "service" may refer either to the service
# itself -- also known as the "service technology" -- or to the configured
# service. Each ConfiguredService record is a configured service, not a service
# technology. However, ConfiguredService uses single table inheritance, and
# there is a different ConfiguredService subclass for each service technology.
# Subclasses also define class methods that return information about the service
# technology.
#
class ConfiguredService < ApplicationRecord
  include ModelAttributes::Name
  include ConfiguredService::Type
end

app/models/configured_services/gmail.rb
require 'googleauth'
require 'google/api_client/client_secrets'
require 'google/apis/gmail_v1'

class ConfiguredServices::Gmail < ConfiguredService
  include Draftable

  provides :data_destination
  with_terminology service: 'Gmail', configured_service: 'account',
                   data_destination: 'recipient list'
  oauthable
  with_draft_attribute :data_destination_configured_service_id

  TOKEN_STATUSES = %i[never_connected safely_connected almost_disconnected
                      disconnected].freeze

  class Authorization
    OAUTH_SCOPES = [
      # We request this for access to the user's email address.
      'https://www.googleapis.com/auth/gmail.metadata',
      'https://www.googleapis.com/auth/gmail.send'
    ].freeze

    def client
      client = client_secrets.to_authorization
      client.scope = OAUTH_SCOPES
      client.redirect_uri = client_secrets.redirect_uris.first
      client
    end

    def authorization_uri(configured_service)
      client = self.client
      raise "ConfiguredService#id can't be blank" if configured_service.id.nil?
      client.state = configured_service.id
      client.additional_parameters = {
        'access_type' => 'offline',
        'include_granted_scopes' => 'true'
      }
      client.authorization_uri.to_s
    end

    def user_authorizer
      @user_authorizer ||= begin
        client_id = Google::Auth::ClientId.from_hash(client_secrets.to_hash)
        Google::Auth::UserAuthorizer.new(client_id, OAUTH_SCOPES,
                                         OauthToken.google_token_store)
      end
    end

    protected

    def client_secrets
      @client_secrets ||= begin
        options = ActiveSupport::JSON.decode(ENV.fetch('GOOGLE_CLIENT_SECRETS'))
        Google::APIClient::ClientSecrets.new(options)
      end
    end
  end

  class_attribute :authorization, instance_accessor: false,
                  instance_predicate: false
  self.authorization = Authorization.new

  def self.authorization=(authorization)
    raise NotImplementedError
  end

  def authorization_uri
    self.class.authorization.authorization_uri(self)
  end

  def token_status
    if oauth_token.nil?
      :never_connected
    else
      seconds = oauth_token.seconds_to_expiration
      if seconds == 0
        :disconnected
      elsif seconds < 60
        :almost_disconnected
      else
        :safely_connected
      end
    end
  end

  TOKEN_STATUSES.each do |status|
    define_method("#{status}?") { token_status == status }
  end

  def gmail
    service = Google::Apis::GmailV1::GmailService.new
    application_name = Rails.application.class.parent_name.titleize
    service.client_options.application_name = application_name
    user_authorizer = self.class.authorization.user_authorizer
    service.authorization = user_authorizer.get_credentials(id.to_s)
    service
  end

  def email_address
    @email_address ||= reload_email_address
  end

  # TODO: Update method logic once we start automatically refreshing tokens.
  def reload_email_address
    raise 'invalid token status' unless safely_connected?
    @email_address = gmail.get_user_profile('me').email_address
  end
end

app/models/configured_services/odk.rb
class ConfiguredServices::Odk < ConfiguredService
  include Draftable

  provides :data_source
  with_terminology service: 'ODK Aggregate', configured_service: 'server',
                   data_source: 'form'
  with_draft_attribute :data_source_configured_service_id

  with_settings :url
  validate :validate_url

  protected

  def validate_url
    message = if !url.is_a?(String)
                'URL is invalid'
              elsif url.blank?
                "URL can't be blank"
              end
    errors.add :settings, message unless message.nil?
  end
end

app/controllers/configured_services_controller.rb
class ConfiguredServicesController < ApplicationController
  include ConfiguredServicePathHelpers

  before_action :set_service, only: [:edit, :update, :destroy]
  before_action :set_service_class
  before_action :add_configured_service_breadcrumb,
                except: [:create, :update, :destroy]

  def index
    # If there is no valid :type parameter, show all configured services.
    @service_class ||= ConfiguredService
    @services = @service_class.order_by_name.load
  end

  def new
    @service = @service_class.new
    render_new
  end

  def create
    @service = @service_class.new(service_params)
    if @service.save
      if @service_class.oauthable?
        # We still need the user to authenticate the configured service.
        redirect_to edit_configured_service_path(@service)
      else
        @service.save_draft
        redirect_to new_integration_path
      end
    else
      render_new
    end
  end

  def edit
    render_edit
  end

  def update
    if @service.update(service_params)
      redirect_to typed_configured_services_path
    else
      render_edit
    end
  end

  def destroy
    @service.destroy
    redirect_to typed_configured_services_path
  end

  protected

  def set_service
    @service = ConfiguredService.find(params[:id])
  end

  # Sets @service_class to the ConfiguredService subclass whose demodulized name
  # equals params[:type]. If there is no such class, the user is redirected to
  # #index, which will list all configured services regardless of type.
  def set_service_class
    if @service.present?
      @service_class = @service.class
    else
      if !params[:type].is_a?(String)
        is_valid = false
      else
        type = 'ConfiguredServices::' + params[:type]
        is_valid = ConfiguredService.type_class_names.include?(type)
      end
      if is_valid
        @service_class = type.constantize
      elsif action_name != 'index'
        redirect_to configured_services_path
      end
    end
  end

  def render_new
    add_breadcrumb 'Add ' +
                   @service_class.terminology.configured_service.titleize
    render 'new'
  end

  def service_params
    settings = @service_class.supported_settings.map(&:to_sym)
    params.permit(:name, settings: settings)
  end

  def render_edit
    add_breadcrumb @service.name
    render 'edit'
  end
end

app/helpers/configured_services_helper.rb
module ConfiguredServicesHelper
  def render_fields
    render @service_class.name.demodulize.underscore + '_fields'
  end
end

app/views/configured_services/_form_fields.html.erb
<div class="form-group">
  <%= label_tag :name, nil, class: 'col-md-1 control-label' %>
  <div class="col-md-6">
    <%= text_field_tag :name, @service.name, placeholder: 'Name',
                       required: true, class: 'form-control' %>
  </div>
</div>
<div class="form-group">
  <%= label_tag 'settings[url]', 'URL', class: 'col-md-1 control-label' %>
  <div class="col-md-11">
    <%= text_field_tag 'settings[url]', @service.settings['url'],
                       placeholder: 'URL', required: true,
                       class: 'form-control' %>
  </div>
</div>
<%# TODO: Extend this UI beyond ODK. %>
<%= hidden_field_tag :type, 'ConfiguredServices::Odk' %>

app/views/configured_services/_gmail_fields.html.erb
<div class="form-group">
  <%= label_tag :name, nil, class: 'col-md-1 control-label' %>
  <div class="col-md-6">
    <%= text_field_tag :name, @service.name, placeholder: 'Name',
                       required: true, class: 'form-control' %>
  </div>
</div>
<% if @service.id.present? %>
  <div class="alert alert-info col-md-offset-1 col-md-11">
    <p>
      <% status = @service.token_status %>
      <% case status %>
      <% when :never_connected %>
        Connect this account to Gmail to enable integrations.
      <% when :safely_connected, :almost_disconnected %>
        This account is connected to Gmail for the next
        <%# For status == :almost_disconnected, seconds may even be 0 at this
            point. In that case, the language that follows will be out-of-date.
            However, that should be unproblematic, because the link below always
            points to the same URL. %>
        <% seconds = @service.oauth_token.seconds_to_expiration %>
        <% minutes = seconds >= 60 ? seconds / 60 : 1 %>
        <%= minutes %> <%= minutes == 1 ? 'minute' : 'minutes' %>.
        Refresh the connection to extend.
      <% when :disconnected %>
        This account’s connection to Gmail has expired. Reconnect it to enable
        integrations.
      <% else %>
        <% raise NotImplementedError %>
      <% end %>
    </p>
    <p>
      <%= link_to @service.authorization_uri, class: 'btn btn-primary',
                  role: :button do %>
        <%= icon('external-link-square') %>

        <% case status %>
        <% when :never_connected %>
          Connect
        <% when :safely_connected, :almost_disconnected %>
          Refresh
        <% when :disconnected %>
          Reconnect
        <% else %>
          <% raise NotImplementedError %>
        <% end %>
      <% end %>
    </p>
  </div>
<% end %>

app/views/configured_services/_odk_fields.html.erb
<div class="form-group">
  <%= label_tag :name, nil, class: 'col-md-1 control-label' %>
  <div class="col-md-6">
    <%= text_field_tag :name, @service.name, placeholder: 'Name',
                       required: true, class: 'form-control' %>
  </div>
</div>
<div class="form-group">
  <%= label_tag 'settings[url]', 'URL', class: 'col-md-1 control-label' %>
  <div class="col-md-11">
    <%= text_field_tag 'settings[url]', @service.settings['url'],
                       placeholder: 'URL', required: true,
                       class: 'form-control' %>
  </div>
</div>

app/views/configured_services/edit.html.erb
<%= form_tag configured_service_path(@service), method: :patch,
             class: 'form-horizontal' do %>
  <%= render_fields %>

  <div class="form-group">
    <div class="col-md-offset-1 col-md-11">
      <%= button_tag icon('floppy-o', 'Save'), class: 'btn btn-default' %>
      <%= link_to icon('close', 'Cancel'), :back, role: :button,
                  class: 'btn btn-default' %>
      <%= link_to icon('trash-o', 'Delete'), configured_service_path(@service),
                  method: :delete, class: 'btn btn-danger btn-delete',
                  role: :button, data: {
                  confirm: "Are you sure you want to delete #{@service.name}?" } %>
    </div>
  </div>
<% end %>

app/views/configured_services/index.html.erb
<div class="collection-actions">
  <% term = @service_class.terminology.configured_service.titleize %>
  <%= link_to icon('plus', 'Add ' + term),
              new_configured_service_path(type: params[:type]),
              role: :button, class: 'btn btn-success' %>
</div>

<% if @services.none? %>
  <div class="panel panel-default">
    <div class="panel-body">
      No <%= @service_class.terminology.configured_service.pluralize %> have
      been configured yet.
    </div>
  </div>
<% else %>
  <table class="table table-hover table-borderless">
    <tbody>
      <% @services.each do |service| %>
        <tr>
          <td>
            <span class="member-actions">
              <%= link_to icon('pencil'),
                          edit_configured_service_path(service) %>
              <% if service.class.provides? :data_source %>
                <%= link_to icon('files-o'),
                            configured_service_data_sources_path(service) %>
              <% elsif service.class.provides? :data_destination %>
                <%= link_to icon('files-o'),
                            configured_service_data_destinations_path(service) %>
              <% end %>
              <%= link_to icon('trash-o', class: 'text-danger'),
                          configured_service_path(service), method: :delete,
                          data: { confirm: "Are you sure you want to delete #{service.name}?" } %>
            </span>
            <%= service.name %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/configured_services/new.html.erb
<%= form_tag configured_services_path(type: params[:type]), method: :post,
             class: 'form-horizontal' do %>
  <%= render_fields %>

  <div class="form-group">
    <div class="col-md-offset-1 col-md-11">
      <% term = @service_class.terminology.configured_service.titleize %>
      <%= button_tag icon('plus', 'Add ' + term), class: 'btn btn-success' %>
      <%= link_to icon('close', 'Cancel'), :back, role: :button,
                  class: 'btn btn-default' %>
    </div>
  </div>
<% end %>