config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'integrations#index'

  resources :configured_services, except: :show do
    resources :data_sources, except: :show do
      member do
        # This is the route for data sources pushing to the app, not for the app
        # itself pushing.
        post 'push'
      end
    end
    resources :data_destinations, except: :show
  end
  resources :integrations, only: [:index, :new, :create, :destroy] do
    collection do
      post 'save_draft'
    end
  end

  namespace :oauth do
    get :google
  end
end

app/models/concerns/data_destination/type.rb
# This module includes functionality for the data destination type, including
# single table inheritance. Follow these steps to add a new data destination
# type:
#
#   1. Define a class for the data destination type in the DataDestinations
#      module, for example, DataDestinations::Gmail.
#   2. Add the demodulized class name (for example, 'Gmail') to
#      TYPE_CLASS_NAMES.
#   3. See ModelAttributes::Settings for ways to store data destination
#      settings.
#
module DataDestination::Type
  extend ActiveSupport::Concern

  include ModelAttributes::Type
  include ModelAttributes::Settings
  include DataDestination::Type::HasMessenger

  # Whitelist of demodulized names of data destination classes
  TYPE_CLASS_NAMES = %w[Gmail].freeze

  class_methods do
    def type_class_names
      TYPE_CLASS_NAMES.map { |name| "DataDestinations::#{name}" }
    end
  end
end

app/models/concerns/data_destination/type/has_messenger.rb
module DataDestination::Type::HasMessenger
  extend ActiveSupport::Concern

  included do
    class_attribute :_messenger, instance_accessor: false,
                    instance_predicate: false
    self._messenger = Messenger::Logger
  end

  class_methods do
    def with_messenger(messenger)
      self._messenger = messenger
    end

    def messenger_class
      _messenger
    end
  end

  def messenger
    self.class.messenger_class.new(self)
  end
end

app/models/concerns/data_destination/type/messenger.rb
module DataDestination::Type::Messenger
  extend ActiveSupport::Concern

  included do
    class_attribute :_messenger, instance_accessor: false,
                    instance_predicate: false
    self._messenger = ::Messenger::Logger
  end

  class_methods do
    def with_messenger(messenger)
      self._messenger = messenger
    end

    def messenger_class
      _messenger
    end
  end

  def messenger
    self.class.messenger_class.new(self)
  end
end

app/models/data_destination.rb
class DataDestination < ApplicationRecord
  include Draftable
  include ModelAttributes::Name
  include ServiceProvided
  include DataDestination::Type

  with_draft_attribute :data_destination_id

  has_many :alerts, dependent: :destroy
end

app/models/data_destinations/gmail.rb
class DataDestinations::Gmail < DataDestination
  with_messenger Messenger::Gmail

  with_settings :email_list
  before_validation :normalize_email_list
  validate :validate_email_list

  # Splits the String email_list to a String Array of email addresses, returning
  # nil if email_list is not String and cannot be split.
  def emails
    email_list.is_a?(String) ? email_list.split(',') : nil
  end

  protected

  def normalize_email_list
    emails = self.emails
    return if emails.nil?
    emails.each(&:strip!)
    emails.uniq!
    self.email_list = emails.join(',')
  end

  # TODO: Make this validation more robust?
  def validate_email_list
    emails = self.emails
    if emails.nil?
      message = 'Email list is invalid'
    elsif emails.blank?
      message = 'Email list can’t be blank'
    else
      emails.each do |email|
        message = if email.blank?
                    'Email can’t be blank'
                  elsif email =~ /\s/
                    'Email can’t contain whitespace'
                  end
        break if message.present?
      end
    end
    errors.add :settings, message if message.present?
  end
end

app/controllers/data_destinations_controller.rb
class DataDestinationsController < ApplicationController
  include ConfiguredServicePathHelpers

  before_action :set_service
  before_action :set_destination, only: [:edit, :update, :destroy, :push]

  before_action do
    add_configured_service_breadcrumb
    add_breadcrumb @service.name, edit_configured_service_path(@service)
    add_breadcrumb @service.class.terminology.data_destination.pluralize.titleize,
                   configured_service_data_destinations_path(@service)
  end

  def index
    @destinations = @service.data_destinations.order_by_name.load
  end

  def new
    @destination = @service.class.data_destination_class.new
    render_new
  end

  def create
    @destination = DataDestination.new(destination_params)
    if @destination.save
      @destination.save_draft
      redirect_to new_integration_path
    else
      render_new
    end
  end

  def edit
    render_edit
  end

  def update
    if @destination.update(destination_params)
      redirect_to configured_service_data_destinations_path(@service)
    else
      render_edit
    end
  end

  def destroy
    @destination.destroy
    redirect_to configured_service_data_destinations_path(@service)
  end

  protected

  def set_service
    @service = ConfiguredService.find(params[:configured_service_id])
  end

  def set_destination
    @destination = @service.data_destinations.find(params[:id])
  end

  def render_new
    add_breadcrumb 'Add ' + @service.class.terminology.data_destination.titleize
    render 'new'
  end

  def destination_params
    destination_class = @service.class.data_destination_class
    settings = destination_class.supported_settings.map(&:to_sym)
    destination_params = params.permit(:configured_service_id, :name,
                                       settings: settings)
    destination_params[:type] = destination_class.name
    destination_params
  end

  def render_edit
    add_breadcrumb @destination.name
    render 'edit'
  end
end

app/views/data_destinations/_form_errors.html.erb
<% if @destination.errors.any? %>
  <div class="panel panel-danger">
    <div class="panel-heading">
      Invalid <%= @service.class.terminology.data_destination.titleize %>
    </div>
    <div class="panel-body">
      <p>
        There
        <% if @destination.errors.size == 1 %>
          was a problem
        <% else %>
          were problems
        <% end %>
        saving the <%= @service.class.terminology.data_destination %>:
      </p>
      <ul>
        <% @destination.errors.each do |attribute, error| %>
          <li>
            <% unless attribute == :settings %>
              <%= DataDestination.human_attribute_name(attribute) %>
            <% end %>
            <%= error %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/data_destinations/_form_fields.html.erb
<div class="form-group">
  <%= label_tag :name, 'List Name', class: 'col-md-2 control-label' %>
  <div class="col-md-6">
    <%= text_field_tag :name, @destination.name,
                       placeholder: 'A name for the list', required: true,
                       class: 'form-control' %>
  </div>
</div>
<div class="form-group">
  <%= label_tag 'settings[email_list]', 'Emails',
                class: 'col-md-2 control-label' %>
  <div class="col-md-10">
    <%= text_area_tag 'settings[email_list]', @destination.emails&.join(', '),
                       placeholder: 'Emails separated by commas',
                       required: true, class: 'form-control' %>
  </div>
</div>

app/views/data_destinations/edit.html.erb
<%= render 'form_errors' %>

<%= form_tag configured_service_data_destination_path(@service, @destination),
             method: :patch, class: 'form-horizontal' do %>
  <%= render 'form_fields' %>

  <div class="form-group">
    <div class="col-md-offset-2 col-md-10">
      <%= button_tag icon('floppy-o', 'Save'), class: 'btn btn-default' %>
      <%= link_to icon('close', 'Cancel'),
                  configured_service_data_destinations_path(@service),
                  role: :button, class: 'btn btn-default' %>
      <%= link_to icon('trash-o', 'Delete'),
                  configured_service_data_destination_path(@service, @destination),
                  method: :delete, role: :button,
                  class: 'btn btn-danger btn-delete',
                  data: { confirm: "Are you sure you want to delete #{@destination.name}?" } %>
    </div>
  </div>
<% end %>

app/views/data_destinations/index.html.erb
<div class="collection-actions">
  <% term = @service.class.terminology.data_destination.titleize %>
  <%= link_to icon('plus', 'Add ' + term),
              new_configured_service_data_destination_path(@service),
              role: :button, class: 'btn btn-success' %>
</div>

<% if @destinations.none? %>
  <div class="panel panel-default">
    <div class="panel-body">
      No <%= @service.class.terminology.data_destination.pluralize %> have been
      configured yet for <strong><%= @service.name %></strong>.
    </div>
  </div>
<% else %>
  <table class="table table-hover table-borderless">
    <tbody>
      <% @destinations.each do |destination| %>
        <tr>
          <td>
            <span class="member-actions">
              <%= link_to icon('pencil'),
                          edit_configured_service_data_destination_path(@service, destination) %>
              <%= link_to icon('trash-o', class: 'text-danger'),
                          configured_service_data_destination_path(@service, destination),
                          method: :delete,
                          data: { confirm: "Are you sure you want to delete #{destination.name}?" } %>
            </span>
            <%= destination.name %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/data_destinations/new.html.erb
<%= render 'form_errors' %>

<%= form_tag configured_service_data_destinations_path(@service), method: :post,
             class: 'form-horizontal' do %>
  <%= render 'form_fields' %>

  <div class="form-group">
    <div class="col-md-offset-2 col-md-10">
      <% term = @service.class.terminology.data_destination.titleize %>
      <%= button_tag icon('plus', 'Add ' + term), class: 'btn btn-success' %>
      <%= link_to icon('close', 'Cancel'), :back, role: :button,
                  class: 'btn btn-default' %>
    </div>
  </div>
<% end %>