config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'integrations#index'

  resources :configured_services, except: :show do
    resources :data_sources, except: :show do
      member do
        # This is the route for data sources pushing to the app, not for the app
        # itself pushing.
        post 'push'
      end
    end
    resources :data_destinations, except: :show
  end
  resources :integrations, only: [:index, :new, :create, :destroy] do
    collection do
      post 'save_draft'
    end
  end

  namespace :oauth do
    get :google
  end
end

app/controllers/integrations_controller.rb
class IntegrationsController < ApplicationController
  add_breadcrumb 'My Integrations', :integrations_path, except: :index

  # For draft updates, maps rule_data keys to their associated parameter keys.
  RULE_DATA_DRAFT_PARAMS = {
    field_name: [:rule_field_name],
    value: %i[numeric_rule_value string_rule_value regexp_match_value],
    case_sensitive: [:rule_case_sensitive]
  }.freeze

  def index
    @source_alerts = DataSourceAlert
                       .joins(:alert, data_source: :configured_service)
                       .reorder(<<-SQL)
                         configured_services.name,
                         data_sources.name,
                         alerts.rule_data ->> 'field_name',
                         data_source_alerts.created_at
                         SQL
                       .load
    add_breadcrumb 'My Integrations' if @source_alerts.any?
  end

  def new
    @source_services = ConfiguredServices::Odk.order_by_name
    @sources = DataSources::Odk.order_by_name
    @destination_services = ConfiguredServices::Gmail.order_by_name.load
    @destinations = DataDestinations::Gmail.order_by_name.load
    @alert = Alert.new
    set_draft
    add_breadcrumb 'Add Integration'
  end

  def create
    Alert.create_for_data_source(integration_params)
    # TODO: Error handling.
    redirect_to integrations_path
  end

  def destroy
    Alert.find(params[:id]).destroy
    redirect_to integrations_path
  end

  def save_draft
    Alert.draft.dependably_update(draft_params)
    head :ok
  end

  protected

  def set_draft
    @draft = Alert.draft
    service = @draft.data_destination_configured_service
    if service && service.class.oauthable? && !service.safely_connected?
      @draft.dependably_update(data_destination_configured_service_id: nil)
    end
  end

  def validate_rule_type_param!
    source = DataSource.find(params[:data_source_id])
    supported_rules = source.class.supported_rules
    if supported_rules.none? { |rule_class| rule_class.name == params[:rule_type] }
      raise ArgumentError
    end
  end

  def integration_params
    validate_rule_type_param!
    rule_data_keys = params.require(:rule_data).keys
    # Permit rule_data parameters whose values are permitted scalars.
    params.permit :data_source_id, :data_destination_id, :rule_type,
                  { rule_data: rule_data_keys }, :message
  end

  def draft_rule_data
    RULE_DATA_DRAFT_PARAMS.reduce({}) do |rule_data, (rule_data_key, param_keys)|
      param_keys.each do |param_key|
        if params.key? param_key
          rule_data[rule_data_key] = params.permit(param_key).fetch(param_key)
          break
        end
      end
      rule_data
    end
  end

  def draft_params
    draft_params = params.permit(
      :data_source_configured_service_id, :data_source_id, :rule_type, :message,
      :data_destination_configured_service_id, :data_destination_id
    )
    draft_params[:rule_data] = draft_rule_data if params.key?(:rule_type)
    draft_params
  end
end

app/helpers/integrations_helper.rb
module IntegrationsHelper
  def dynamic_rule_fields(rule_class)
    if rule_class < Rules::Odk::NumericOperator
      'numeric_rule_value'
    elsif rule_class == Rules::Odk::RegexpMatch
      'regexp_match_value rule_case_sensitive'
    elsif rule_class < Rules::Odk::StringOperator
      'string_rule_value rule_case_sensitive'
    else
      raise NotImplementedError
    end
  end

  def draft_rule_value(rule_class, except: nil)
    if @draft.rule_type.blank? || @draft.rule_data.blank? ||
      !(@draft.rule_class <= rule_class) || excepted_rule_class?(except)
      return nil
    end
    @draft.rule_data['value']
  end

  protected

  def excepted_rule_class?(except)
    return false unless except
    if except.is_a? Enumerable
      except.any? { |klass| @draft.rule_class <= klass }
    else
      @draft.rule_class <= except
    end
  end
end

app/views/integrations/_choices_alert.html.erb
<div class="choices" id="choices-alert">
  <%= content_tag :div, class: 'panel panel-default choice',
                  id: 'choice-pattern',
                  data: { has_draft: @draft.rule_type.present? } do %>
    <div class="panel-heading">
      <h5 class="panel-title"><span>Choose a Pattern</span></h5>
    </div>
    <div class="panel-body">
      <form>
        <div class="form-group">
          <%= label_tag 'rule_field_name', 'Send an alert about the field' %>
          <div class="row">
            <div class="col-xs-7">
              <%= text_field_tag 'rule_field_name',
                                 @draft.rule_data&.[]('field_name'),
                                 placeholder: 'Field name', required: true,
                                 class: 'form-control' %>
            </div>
          </div>
        </div>
        <div class="form-group" id="rule_class_name_form_group">
          <%= label_tag 'rule_class_name',
                        'If a data point&hellip;'.html_safe %>
          <div class="row">
            <div class="col-xs-6">
              <%= content_tag :select, id: :rule_class_name,
                              name: :rule_class_name, class: 'form-control',
                              required: true,
                              data: { draft_name: :rule_type } do %>
                <% first = true %>
                <optgroup label="Numeric rules">
                  <% DataSources::Odk.supported_rules.each do |rule_class| %>
                    <% if rule_class < Rules::Odk::StringOperator && first %>
                      </optgroup>
                      <optgroup label="Text rules">
                      <% first = false %>
                    <% end %>

                    <%= content_tag :option, rule_class.title.upcase_first,
                                    value: rule_class.name,
                                    selected: rule_class.name == @draft.rule_type,
                                    data: { fields: dynamic_rule_fields(rule_class) } %>
                  <% end %>
                </optgroup>
              <% end %>
            </div>
          </div>
        </div>
        <div class="form-group dynamic-rule-field">
          <div class="row">
            <div class="col-xs-6">
              <%= number_field_tag 'numeric_rule_value',
                                   draft_rule_value(Rules::Odk::NumericOperator),
                                   placeholder: 'Number', step: :any,
                                   class: 'form-control',
                                   data: { rule_data_name: 'value',
                                   required: true } %>
            </div>
          </div>
        </div>
        <div class="form-group dynamic-rule-field">
          <div class="row">
            <div class="col-xs-6">
              <% value = draft_rule_value(Rules::Odk::StringOperator,
                                          except: Rules::Odk::RegexpMatch) %>
              <%= text_field_tag 'string_rule_value', value,
                                 placeholder: 'Text', class: 'form-control',
                                 data: { rule_data_name: 'value',
                                 required: true } %>
            </div>
          </div>
        </div>
        <div class="form-group dynamic-rule-field">
          <%= text_field_tag 'regexp_match_value',
                             draft_rule_value(Rules::Odk::RegexpMatch),
                             placeholder: 'Regular expression',
                             class: 'form-control',
                             data: { rule_data_name: 'value',
                             required: true } %>
        </div>
        <div class="checkbox dynamic-rule-field">
          <label>
            <%= hidden_field_tag 'rule_case_sensitive', false %>
            <%= check_box_tag 'rule_case_sensitive', true,
                              @draft.rule_data&.[]('case_sensitive') == 'true' %>
            Case-sensitive
          </label>
        </div>
        <%= button_tag 'Use This Pattern',
                       class: 'btn btn-primary action action-complete' %>
        <div class="action action-revisit">
          <%= link_to icon('pencil'), '#', role: :button %>
          <%= link_to 'Change', '#', role: :button %>
        </div>
      </form>
    </div>
  <% end %>

  <%= content_tag :div, class: 'panel panel-default choice',
                  id: 'choice-message',
                  data: { has_draft: @draft.message.present? } do %>
    <div class="panel-heading">
      <h5 class="panel-title"><span>Add a Message</span></h5>
    </div>
    <div class="panel-body">
      <form class="form-inline form-paragraph">
        <div class="row">
          <div class="form-paragraph-text col-xs-12">
            Choose a message to send with the alert.
          </div>
        </div>
        <div class="row">
          <div class="form-group col-xs-12">
            <%= text_area_tag 'alert_message', @draft.message,
                              placeholder: 'Message', required: true,
                              class: 'form-control form-inline-input-12',
                              data: { draft_name: :message } %>
          </div>
        </div>
        <%= button_tag 'Use This Message',
                       class: 'btn btn-primary action action-complete' %>
        <div class="action action-revisit">
          <%= link_to icon('pencil'), '#', role: :button %>
          <%= link_to 'Change', '#', role: :button %>
        </div>
      </form>
    </div>
  <% end %>
</div>

app/views/integrations/_choices_data_destination.html.erb
<div class="choices" id="choices-data-destination">
  <p>Choose how the alert will be delivered.</p>

  <div class="choice row" id="choice-data-destination-service">
    <% %i[gmail sms google_sheets].each.with_index do |service, i| %>
      <% if @draft.data_destination_configured_service_id.blank? ||
          service == :gmail %>
        <%= content_tag :div, class: 'service col-xs-3',
                        id: "service-#{service}" do %>
          <p>
            <%= link_to image_tag("services/#{service}"), '#', role: :button %>
          </p>
        <% end %>
      <% end %>
    <% end %>
  </div>

  <div class="choices" id="choices-gmail">
  <% has_draft = @draft.data_destination_configured_service_id.present? %>
  <%= content_tag :div, class: 'panel panel-default choice choice-radio',
                  id: 'choice-gmail-account',
                  data: { has_draft: has_draft } do %>
    <div class="panel-heading">
      <h5 class="panel-title"><span>Choose an Account</span></h5>
    </div>
    <div class="panel-body">
      <p>Choose the Gmail account that will send the alert.</p>
      <form>
        <% draft_id = @draft.data_destination_configured_service_id ||
                      @destination_services.first&.id %>
        <% @destination_services.each.with_index do |service| %>
          <% connected = service.safely_connected? %>
          <%= content_tag :div,
                          class: 'radio' + (!connected ? ' disabled' : '') do %>
            <label>
              <% html_class = !connected ? 'permanently-disabled' : nil %>
              <%= radio_button_tag 'data_destination_configured_service_id',
                                   service.id,
                                   service.id == draft_id && connected,
                                   class: html_class, required: true,
                                   disabled: !connected %>
              <%= content_tag :strong, service.name,
                             class: !connected ? 'text-muted' : nil %>
              <% if connected %>
                <%= service.email_address %>
              <% else %>
                <%= link_to service.never_connected? ? 'Connect' : 'Reconnect',
                            service.authorization_uri %>
              <% end %>
            </label>
          <% end %>
        <% end %>

        <p class="action action-add">
          <%= link_to icon('plus'), new_configured_service_path(type: 'Gmail') %>
          <%= link_to 'Add a New Account', new_configured_service_path(type: 'Gmail') %>
        </p>
        <%= button_tag 'Use This Account',
                       class: 'btn btn-primary action action-complete' %>
        <div class="action action-revisit">
          <%= link_to icon('pencil'), '#', role: :button %>
          <%= link_to 'Change', '#', role: :button %>
        </div>
      </form>
    </div>
  <% end %>

  <%= content_tag :div, class: 'panel panel-default choice choice-radio',
                  id: 'choice-recipient-list',
                  data: { has_draft: @draft.data_destination_id.present? } do %>
    <div class="panel-heading">
      <h5 class="panel-title"><span>Choose a Recipient List</span></h5>
    </div>
    <div class="panel-body">
      <p>Choose who will receive the alert.</p>
      <form>
        <% draft_id = @draft.data_destination_id || @destinations.first&.id %>
        <% @destinations.each.with_index do |destination| %>
          <%= content_tag :div, class: 'radio', data: {
                          configured_service_id: destination.configured_service_id } do %>
            <label>
              <%= radio_button_tag 'data_destination_id', destination.id,
                                   destination.id == draft_id, required: true %>
              <strong><%= destination.name %></strong>
              <%= destination.emails.join(', ') %>
            </label>
          <% end %>
        <% end %>

        <%= content_tag :p, class: 'action action-add', data: {
                        path: new_configured_service_data_destination_path(0) } do %>
          <%= link_to icon('plus'), '#' %>
          <%= link_to 'Add a New Recipient List', '#' %>
        <% end %>
        <%= button_tag 'Use This Recipient List',
                       class: 'btn btn-primary action action-complete' %>
        <div class="action action-revisit">
          <%= link_to icon('pencil'), '#', role: :button %>
          <%= link_to 'Change', '#', role: :button %>
        </div>
      </form>
    </div>
  <% end %>
  </div>
</div>

app/views/integrations/_choices_data_source.html.erb
<div class="choices" id="choices-data-source">
  <div class="choice row" id="choice-data-source-service">
    <% %i[odk      dhis2        ona     disarm
          commcare medic_mobile opensrp rapidpro].each.with_index do |service, i| %>
      <% if @draft.data_source_configured_service_id.blank? ||
            service == :odk %>
        <%= content_tag :div, class: 'service col-xs-3',
                        id: "service-#{service}" do %>
          <p>
            <%= link_to image_tag("services/#{service}"), '#', role: :button %>
          </p>
        <% end %>
      <% end %>
    <% end %>
  </div>

  <div class="choices" id="choices-odk">
    <% has_draft = @draft.data_source_configured_service_id.present? %>
    <%= content_tag :div, class: 'panel panel-default choice choice-radio',
                    id: 'choice-server', data: { has_draft: has_draft } do %>
      <div class="panel-heading">
        <h5 class="panel-title"><span>Choose a Server</span></h5>
      </div>
      <div class="panel-body">
        <form>
          <% @source_services.each.with_index do |service, i| %>
            <div class="radio">
              <label>
                <% if @draft.data_source_configured_service_id.present? %>
                  <% checked = service.id == @draft.data_source_configured_service_id %>
                <% else %>
                  <% checked = i == 0 %>
                <% end %>
                <%= radio_button_tag 'data_source_configured_service_id',
                                     service.id, checked, required: true %>
                <strong><%= service.name %></strong> <%= service.url %>
              </label>
            </div>
          <% end %>

          <p class="action action-add">
            <%= link_to icon('plus'), new_configured_service_path(type: 'Odk') %>
            <%= link_to 'Add a New Server', new_configured_service_path(type: 'Odk') %>
          </p>
          <%= button_tag 'Use This Server',
                         class: 'btn btn-primary action action-complete' %>
          <div class="action action-revisit">
            <%= link_to icon('pencil'), '#', role: :button %>
            <%= link_to 'Change', '#', role: :button %>
          </div>
        </div>
      </form>
    <% end %>

    <%= content_tag :div, class: 'panel panel-default choice choice-radio',
                    id: 'choice-form',
                    data: { has_draft: @draft.data_source_id.present? } do %>
      <div class="panel-heading">
        <h5 class="panel-title"><span>Choose a Form</span></h5>
      </div>
      <div class="panel-body">
        <form>
          <% @sources.each.with_index do |source, i| %>
            <%= content_tag :div, class: 'radio', data: {
                            configured_service_id: source.configured_service_id } do %>
              <label>
                <% if @draft.data_source_id.present? %>
                  <% checked = source.id == @draft.data_source_id %>
                <% else %>
                  <% checked = i == 0 %>
                <% end %>
                <%= radio_button_tag 'data_source_id', source.id, checked,
                                     required: true %>
                <strong><%= source.name %></strong> <%= source.form_id %>
              </label>
            <% end %>
          <% end %>

          <%= content_tag :p, class: 'action action-add', data: {
                          path: new_configured_service_data_source_path(0) } do %>
            <%= link_to icon('plus'), '#' %>
            <%= link_to 'Add a New Form', '#' %>
          <% end %>
          <%= button_tag 'Use This Form',
                         class: 'btn btn-primary action action-complete' %>
          <div class="action action-revisit">
            <%= link_to icon('pencil'), '#', role: :button %>
            <%= link_to 'Change', '#', role: :button %>
          </div>
        </form>
      </div>
    <% end %>
  </div>
</div>

app/views/integrations/_finalize_integration.erb
<div id="finalize-integration">
  <div class="alert alert-info">
    <p>Set up ODK Aggregate to publish to the following URL:</p>
    <p class="small">
      <%= tag :strong, id: 'push-url', data: {
              url: push_configured_service_data_source_url(0, 1) } %>
    </p>
  </div>

  <%= form_tag integrations_path, method: :post do %>
    <% names = %w[data_source_id rule_data[field_name] rule_type
                  rule_data[value] rule_data[case_sensitive] message
                  data_destination_id] %>
    <% names.each do |name| %>
      <%= hidden_field_tag name %>
    <% end %>
    <%= button_tag icon('plus', 'Add Integration'), class: 'btn btn-success' %>
  <% end %>
</div>

app/views/integrations/index.html.erb
<div id="integrations-index">
  <% if @source_alerts.none? %>
    <div class="jumbotron">
      <h1>Take Action on Your Data</h1>
      <p>
        Congenial Enigma searches incoming data for patterns that interest you.
        When it identifies matching data, it takes action &mdash; notifying you
        or sending the data to another app. The result is integrated
        technologies that make the best use of the data you’re collecting.
      </p>
      <p>
        <%= link_to icon('plus', 'Add Integration'), new_integration_path,
                    role: :button, class: 'btn btn-success btn-lg' %>
      </p>
    </div>
  <% else %>
    <div class="collection-actions">
      <%= link_to icon('plus', 'Add Integration'), new_integration_path,
                  role: :button, class: 'btn btn-success' %>
    </div>
    <table class="table">
      <thead>
        <tr>
          <th>Integration</th>
          <th>Server</th>
          <th>Form</th>
          <th>Field</th>
        </tr>
      </thead>
      <tbody>
        <% @source_alerts.each do |source_alert| %>
          <% source = source_alert.data_source %>
          <% alert = source_alert.alert %>
          <tr>
            <td>
              <!-- Integration -->
              Alert
            </td>
            <td>
              <!-- Server -->
              <%= link_to source.configured_service.name,
                          edit_configured_service_path(source.configured_service) %>
            </td>
            <td>
              <!-- Form -->
              <%= link_to source.name,
                          edit_configured_service_data_source_path(source.configured_service, source) %>
            </td>
            <td>
              <!-- Field -->
              <code><%= alert.rule.field_name %></code>
            </td>
          </tr>
          <tr class="integration-details">
            <td colspan="4">
              <div class="well">
                <p>
                  If a data point <%= alert.rule.class.title %>
                  <% if alert.rule.class < Rules::Odk::NumericOperator %>
                    <% number = number_with_precision(alert.rule.value,
                                                      delimiter: ',',
                                                      strip_insignificant_zeros: true) %>
                    <strong><%= number %></strong>,
                  <% elsif alert.rule.class < Rules::Odk::StringOperator %>
                    <% if alert.rule.class == Rules::Odk::RegexpMatch %>
                      <code><%= alert.rule.value %></code>
                    <% else %>
                      <strong>&ldquo;<%= alert.rule.value %>&rdquo;</strong>
                    <% end %>

                    <% if alert.rule.case_sensitive? %>
                      (case-sensitive),
                    <% else %>
                      (case-insensitive),
                    <% end %>
                  <% else %>
                    <% raise NotImplementedError %>
                  <% end %>

                  send the following message to
                  <%= link_to alert.data_destination.name,
                              edit_configured_service_data_destination_path(alert.data_destination.configured_service, alert.data_destination) %>
                  from the
                  <% terms = alert.data_destination.configured_service.class.terminology %>
                  <%= terms.service %> <%= terms.configured_service %>
                  <%= link_to alert.data_destination.configured_service.name,
                              edit_configured_service_path(alert.data_destination.configured_service) %>:
                </p>
                <blockquote><p><%= alert.message %></p></blockquote>

                <%= link_to icon('trash-o', 'Delete'),
                            integration_path(alert.id), method: :delete,
                            role: :button, class: 'btn btn-danger',
                            data: { confirm: 'Are you sure you want to delete the alert?' } %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</div>

app/views/integrations/new.html.erb
<table class="table table-condensed" id="integrations-new">
  <tbody>
    <tr>
      <td><h4>1</h4></td>
      <td>
        <h4>Choose a Data Source</h4>
        <%= render 'choices_data_source' %>
      <td>
    </tr>
    <tr>
      <td><h4 class="text-muted">2</h4></td>
      <td>
        <h4 class="text-muted">Add an Alert</h4>
        <%= render 'choices_alert' %>
      </td>
    </tr>
    <tr>
      <td><h4 class="text-muted">3</h4></td>
      <td>
        <h4 class="text-muted">Choose a Data Destination</h4>
        <%= render 'choices_data_destination' %>
        <%= render 'finalize_integration' %>
      </td>
    </tr>
  </tbody>
</table>